name: Build Website Stage

on:
    push:
        branches: [dev]

    workflow_dispatch:

jobs:
    website:
        name: Build Website
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Image
              id: build_step
              uses: docker/build-push-action@v2
              with:
                  push: true
                  build-args: |
                      "BUILDER=${{ github.actor }}"
                      "VERSION=${{ github.sha }}"
                      "MODE=stage"
                  tags: |
                      ghcr.io/seventv/website/stage:${{ github.sha }}
                      ghcr.io/seventv/website/stage:latest
