name: Website Lint, Build, Deploy

on:
    push:
        branches:
            - master
            - dev
    pull_request:
    workflow_dispatch:
        inputs:
            deploy:
                description: "Deploy location"
                required: true
                default: "none"
                type: choice
                options:
                    - production
                    - staging
                    - none

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        concurrency:
            group: ${{ github.workflow }}-lint-${{ github.ref }}
            cancel-in-progress: true

        steps:
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.18.1

            - name: Setup node env 🏗
              uses: actions/setup-node@v3.0.0
              with:
                  node-version: 18

            - name: Checkout 🛎
              uses: actions/checkout@v3

            - id: cache-paths
              run: |
                  echo "::set-output name=go-build::$(go env GOCACHE)"
                  echo "::set-output name=go-mod::$(go env GOMODCACHE)"

            - name: Go Build Cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.cache-paths.outputs.go-build }}
                  key: ${{ runner.os }}-go-build-${{ hashFiles('go/go.sum') }}

            - name: Go Mod Cache
              uses: actions/cache@v3
              with:
                  path: ${{ steps.cache-paths.outputs.go-mod }}
                  key: ${{ runner.os }}-go-mod-${{ hashFiles('go/go.sum') }}

            - name: Node Modules Cache
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}

            - name: Install dependencies 👨🏻‍💻
              run: |
                  make deps
                  make dev_deps

            - name: Run linter 👀
              run: make lint

            - name: Build App ⚙️
              run: make build

            - name: Upload Website Build
              uses: actions/upload-artifact@v3
              with:
                  name: website-build
                  path: dist
                  retention-days: 3

            - name: Upload Server Build
              uses: actions/upload-artifact@v3
              with:
                  name: server-build
                  path: server/out
                  retention-days: 3

    post-lint:
        name: Post Lint
        runs-on: ubuntu-latest
        needs:
            - lint
        if: ${{ failure() }}

        steps:
            - name: Cancel current workflow run
              uses: actions/github-script@v6
              with:
                  script: |
                      github.actions.cancelWorkflowRun({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          run_id: context.runId
                      })

    build:
        name: Build
        runs-on: self-hosted
        env:
            DEPLOY_PROD: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'production') || (github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master') }}
            DEPLOY_STAGE: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'staging') || (github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'dev') || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'staged')) }}
        concurrency:
            group: ${{ github.workflow }}-build-${{ github.ref }}
            cancel-in-progress: true

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - id: buildx-context
              run: |
                  docker context create builders

            - uses: docker/setup-buildx-action@v2
              id: buildx
              with:
                  install: true
                  endpoint: builders

            - name: "[Production] Build docker image"
              if: ${{ env.DEPLOY_PROD == 'true' }}
              uses: docker/build-push-action@v3
              with:
                  context: .
                  cache-from: |
                      type=gha
                  cache-to: |
                      type=gha,mode=max
                  tags: |
                      website-prod:${{ github.sha }}
                  build-args: |
                      "BUILDER=${{ github.actor }}"
                      "VERSION=${{ github.sha }}"
                      "MODE=prod"
                  outputs: |
                      type=docker,dest=prod-image.tar
                  target: final

            - name: "[Production] Upload docker image"
              if: ${{ env.DEPLOY_PROD == 'true' }}
              uses: actions/upload-artifact@v3
              with:
                  name: production-docker-image
                  path: prod-image.tar
                  retention-days: 3

            - name: "[Staging] Build docker image"
              if: ${{ env.DEPLOY_STAGE == 'true' }}
              uses: docker/build-push-action@v3
              with:
                  context: .
                  cache-from: |
                      type=gha
                  cache-to: |
                      type=gha,mode=max
                  tags: |
                      website-dev:${{ github.sha }}
                  build-args: |
                      "BUILDER=${{ github.actor }}"
                      "VERSION=${{ github.sha }}"
                      "MODE=dev"
                  outputs: |
                      type=docker,dest=dev-image.tar
                  target: final

            - name: "[Staging] Upload docker image"
              if: ${{ env.DEPLOY_STAGE == 'true' }}
              uses: actions/upload-artifact@v3
              with:
                  name: staging-docker-image
                  path: dev-image.tar
                  retention-days: 3

    deploy:
        name: Deploy
        needs:
            - build
            - lint
        env:
            DEPLOY_PROD: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'production') || (github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'master') }}
            DEPLOY_STAGE: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy == 'staging') || (github.event_name == 'push' && github.ref_type == 'branch' && github.ref_name == 'dev') || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'staged')) }}
        if: ${{ (github.event_name == 'workflow_dispatch' && github.event.inputs.deploy != 'none') || (github.event_name == 'push' && github.ref_type == 'branch' && (github.ref_name == 'master' || github.ref_name == 'dev')) || (github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'staged')) }}
        runs-on: self-hosted
        concurrency:
            group: ${{ github.workflow }}-deploy-${{ github.ref }}
            cancel-in-progress: true

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - id: buildx-context
              run: |
                  docker context create builders

            - uses: docker/setup-buildx-action@v2
              id: buildx
              with:
                  install: true
                  endpoint: builders

            - name: Log into Harbor Registry
              uses: docker/login-action@v2
              with:
                  registry: harbor.disembark.dev
                  username: robot$deploy-7tv
                  password: ${{ secrets.REGISTRY_TOKEN }}

            - name: Install kubectl
              uses: azure/setup-kubectl@v2.1

            - name: "[Production] Download artifact"
              uses: actions/download-artifact@v3
              with:
                  name: production-docker-image

            - name: "[Production] Load image"
              run: |
                  docker load --input prod-image.tar
                  docker image ls -a

            - name: "[Production] Tag & Push docker images"
              if: ${{ env.DEPLOY_PROD == 'true' }}
              run: |
                  docker tag website-prod:${{ github.sha }} harbor.disembark.dev/7tv/website:latest
                  docker tag website-prod:${{ github.sha }} harbor.disembark.dev/7tv/website:${{ github.sha }}
                  docker push harbor.disembark.dev/7tv/website:latest
                  docker push harbor.disembark.dev/7tv/website:${{ github.sha }}

            - name: "[Production] Update deployment template"
              uses: danielr1996/envsubst-action@1.1.0
              if: ${{ env.DEPLOY_PROD == 'true' }}
              env:
                  IMAGE_TAG: ${{ github.sha }}
              with:
                  input: k8s/prod.template.yaml
                  output: k8s/prod.yaml

            - name: "[Production] Deploy to k8s"
              if: ${{ env.DEPLOY_PROD == 'true' }}
              env:
                  KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
              run: |
                  mkdir -p ~/.kube
                  (echo $KUBE_CONFIG_DATA | base64 -d) >> ~/.kube/config
                  kubectl config use-context autodeploy@SevenTV

                  kubectl apply -f k8s/prod.yaml

            - name: "[Staging] Download artifact"
              uses: actions/download-artifact@v3
              with:
                  name: staging-docker-image

            - name: "[Production] Load image"
              run: |
                  docker load --input dev-image.tar
                  docker image ls -a

            - name: "[Staging] Tag & Push docker images"
              if: ${{ env.DEPLOY_STAGE == 'true' }}
              run: |
                  docker tag website-dev:${{ github.sha }} harbor.disembark.dev/7tv-stage/website:latest
                  docker tag website-dev:${{ github.sha }} harbor.disembark.dev/7tv-stage/website:${{ github.sha }}
                  docker push harbor.disembark.dev/7tv-stage/website:latest
                  docker push harbor.disembark.dev/7tv-stage/website:${{ github.sha }}

            - name: "[Staging] Update deployment template"
              uses: danielr1996/envsubst-action@1.1.0
              if: ${{ env.DEPLOY_STAGE == 'true' }}
              env:
                  IMAGE_TAG: ${{ github.sha }}
              with:
                  input: k8s/dev.template.yaml
                  output: k8s/dev.yaml

            - name: "[Staging] Deploy to k8s"
              if: ${{ env.DEPLOY_STAGE == 'true' }}
              env:
                  KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG_STAGE }}
              run: |
                  mkdir -p ~/.kube
                  (echo $KUBE_CONFIG_DATA | base64 -d) >> ~/.kube/config
                  kubectl config use-context autodeploy@SevenTV

                  kubectl apply -f k8s/dev.yaml
