name: Crowdin Download Translations

on:
    workflow_dispatch:
    schedule:
        - cron: "0 */6 * * *"

jobs:
    download:
        name: Synchronize with Crowdin
        runs-on: ubuntu-latest
        env:
            UPDATE_BRANCH: ci/update-locale
            BASE_BRANCH: dev
        steps:
            - name: Setup Node
              uses: actions/setup-node@v3.3.0
              with:
                  node-version: 18

            - name: Install Prettier
              run: |
                  yarn global add prettier

            - name: Checkout
              uses: actions/checkout@v3

            - name: Change branch to the update branch
              id: commits
              run: |
                  git pull
                  echo "::set-output name=base::$(git rev-parse origin/${{ env.BASE_BRANCH }})"
                  git rev-parse --quiet origin/${{ env.UPDATE_BRANCH }} || git branch ${{ env.UPDATE_BRANCH }}
                  git checkout ${{ env.UPDATE_BRANCH }}
                  echo "::set-output name=update::$(git rev-parse ${{ env.UPDATE_BRANCH }}~)"

            - name: Download Crowdin Translations
              uses: crowdin/github-action@1.4.10
              with:
                  upload_sources: false
                  upload_translations: false
                  download_translations: true
                  create_pull_request: false
                  source: locale/en_US.ts
                  translation: locale/%locale_with_underscore%.ts
                  token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
                  project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
                  push_translations: false

            - name: Fix Permissions
              run: |
                  echo "debug: $(id -u):$(id -g)"
                  sudo chown -R "$(id -u):$(id -g)" locale
                  node locale/generate_hash.js
                  prettier --write locale

            - name: Count lines
              id: count
              run: |
                  echo "::set-output name=lines::$(git status --porcelain | wc -l)"
