name: Crowdin Action

on:
    push:
        branches: [master]

jobs:
    synchronize-with-crowdin:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: crowdin action
              uses: crowdin/github-action@1.4.9
              with:
                  upload_translations: true
                  source: locale/en_US.ts
                  token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
                  project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
