name: Crowdin Download

on:
    push:
        branches:
            - troy/update

    schedule:
        - cron: "30 * * * *"

jobs:
    download:
        name: Synchronize with Crowdin
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Download Crowdin Translations
              uses: crowdin/github-action@1.4.9
              with:
                  upload_sources: false
                  upload_translations: false
                  download_translations: true
                  create_pull_request: true
                  source: locale/en_US.ts
                  translation: locale/%locale_with_underscore%.ts
                  token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
                  project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
                  push_translations: true
                  pull_request_base_branch_name: troy/update
                  localization_branch_name: ci/update-locale
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
