name: Crowdin Download Translations

on:
    push:
        branches:
            - troy/update

    schedule:
        - cron: "30 * * * *"

jobs:
    download:
        name: Synchronize with Crowdin
        runs-on: ubuntu-latest
        steps:
            - name: Setup Node
              uses: actions/setup-node@v3.0.0
              with:
                  node-version: 18

            - name: Install Prettier
              run: |
                  yarn global add prettier

            - name: Checkout
              uses: actions/checkout@v3

            - name: Download Crowdin Translations
              uses: crowdin/github-action@1.4.9
              with:
                  upload_sources: false
                  upload_translations: false
                  download_translations: true
                  create_pull_request: false
                  source: locale/en_US.ts
                  translation: locale/%locale_with_underscore%.ts
                  token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
                  project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
                  push_translations: false
                  pull_request_base_branch_name: troy/update
                  localization_branch_name: ci/update-locale

            - name: Change branch to the update branch
              run: |
                git pull
                git checkout ci/update-locale || git branch ci/update-locale

            - name: Fix Permissions
              run: sudo chown -R $(id -u):$(id -g) locale

            - name: Prettify code
              run: |
                  prettier --write locale

            - name: Count lines
              id: count
              run: echo "::set-output name=lines::$(git status --porcelain | wc -l)"

            - name: debug run
              run: |
                echo "${{ steps.count.outputs.lines != '0' }}"
                echo "${{ steps.count.outputs.lines }}"

            - name: Create Pull Request
              if: ${{ steps.count.outputs.lines != '0' }}
              uses: peter-evans/create-pull-request@v4
              with:
                  title: Update Locales
                  body: New Crowdin Translations
                  base: troy/update
                  branch: ci/update-locale
                  delete-branch: true
